// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhasFinancas.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinhasFinancas.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321194853_AdicionarCategoriasDinamicas")]
    partial class AdicionarCategoriasDinamicas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.CategoriaDespesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("idx_categorias_despesa_usuario_nome");

                    b.ToTable("categorias_despesa", (string)null);
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.CategoriaReceita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("idx_categorias_receita_usuario_nome");

                    b.ToTable("categorias_receita", (string)null);
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("TipoDespesa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.ToTable("despesas", (string)null);

                    b.HasDiscriminator<string>("TipoDespesa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Divida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateOnly>("DataCompra")
                        .HasColumnType("date")
                        .HasColumnName("data_compra");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("NomeDevedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_devedor");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_dividas_usuario");

                    b.ToTable("dividas", (string)null);
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<Guid>("DespesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("despesa_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<bool>("Paga")
                        .HasColumnType("boolean")
                        .HasColumnName("paga");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("idx_parcelas_vencimento");

                    b.HasIndex("DespesaId");

                    b.ToTable("parcelas", (string)null);
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.ParcelaDivida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<Guid>("DividaId")
                        .HasColumnType("uuid")
                        .HasColumnName("divida_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<bool>("Paga")
                        .HasColumnType("boolean")
                        .HasColumnName("paga");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("DividaId");

                    b.ToTable("parcelas_divida", (string)null);
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly>("DataRecebimento")
                        .HasColumnType("date")
                        .HasColumnName("data_recebimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("boolean")
                        .HasColumnName("recorrente");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DataRecebimento")
                        .HasDatabaseName("idx_receitas_usuario_data");

                    b.ToTable("receitas", (string)null);
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("two_factor_secret");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.DespesaExtra", b =>
                {
                    b.HasBaseType("MinhasFinancas.Domain.Entities.Despesa");

                    b.Property<DateOnly>("DataDespesa")
                        .HasColumnType("date")
                        .HasColumnName("data_despesa");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("forma_pagamento_extra");

                    b.HasDiscriminator().HasValue("Extra");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.DespesaFixa", b =>
                {
                    b.HasBaseType("MinhasFinancas.Domain.Entities.Despesa");

                    b.Property<DateOnly>("DataPrimeiraParcela")
                        .HasColumnType("date")
                        .HasColumnName("data_primeira_parcela");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("forma_pagamento");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.HasDiscriminator().HasValue("Fixa");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.DespesaFixa", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.ParcelaDivida", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.Entities.Divida", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("DividaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("MinhasFinancas.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("MinhasFinancas.Domain.ValueObjects.SenhaHash", "SenhaHash", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("senha_hash");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("SenhaHash")
                        .IsRequired();
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.Divida", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Entities.DespesaFixa", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
